### ISSUE TITLE
error on click edit button to create a background

### ISSUE THREAD

**Issue by rodrigo1593** [ArcadeMakerSources/ArcadeMaker-Demo#8]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at GameStudio.SpriteDesigner..ctor(Bitmap image) in C:\Users\vsprojs\GameStudio\SpriteDesigner.cs:line 64
   at GameStudio.BackgroundEditor.editBtn_Click(Object sender, EventArgs e) in C:\Users\vsprojs\GameStudio\BackgroundEditor.cs:line 67
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ArcadeMaker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/ArcadeMaker.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3081.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CodeAnalysis
    Assembly Version: 4.7.0.0
    Win32 Version: 4.700.23.41609
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/Microsoft.CodeAnalysis.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/System.Collections.Immutable.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/System.Reflection.Metadata.DLL
----------------------------------------
Microsoft.CodeAnalysis.CSharp
    Assembly Version: 4.7.0.0
    Win32 Version: 4.700.23.41609
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/Microsoft.CodeAnalysis.CSharp.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
NAudio
    Assembly Version: 2.2.1.0
    Win32 Version: 2.2.1.0
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/NAudio.DLL
----------------------------------------
NAudio.Core
    Assembly Version: 2.2.1.0
    Win32 Version: 2.2.1.0
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/NAudio.Core.DLL
----------------------------------------
NAudio.WinForms
    Assembly Version: 2.2.1.0
    Win32 Version: 2.2.1.0
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/NAudio.WinForms.DLL
----------------------------------------
NAudio.Wasapi
    Assembly Version: 2.2.1.0
    Win32 Version: 2.2.1.0
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/NAudio.Wasapi.DLL
----------------------------------------
NAudio.WinMM
    Assembly Version: 2.2.1.0
    Win32 Version: 2.2.1.0
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/NAudio.WinMM.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.2
    Win32 Version: 4.6.31308.01
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/System.Numerics.Vectors.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Security.Cryptography.Algorithms/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Globalization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.CodeAnalysis.Workspaces
    Assembly Version: 4.7.0.0
    Win32 Version: 4.700.23.41609
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/Microsoft.CodeAnalysis.Workspaces.DLL
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/System.Threading.Tasks.Extensions.DLL
----------------------------------------
Microsoft.CodeAnalysis.CSharp.Workspaces
    Assembly Version: 4.7.0.0
    Win32 Version: 4.700.23.41609
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/Microsoft.CodeAnalysis.CSharp.Workspaces.DLL
----------------------------------------
Microsoft.CodeAnalysis.Features
    Assembly Version: 4.7.0.0
    Win32 Version: 4.700.23.41609
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/Microsoft.CodeAnalysis.Features.DLL
----------------------------------------
Microsoft.CodeAnalysis.CSharp.Features
    Assembly Version: 4.7.0.0
    Win32 Version: 4.700.23.41609
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/Microsoft.CodeAnalysis.CSharp.Features.DLL
----------------------------------------
System.Composition.TypedParts
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/System.Composition.TypedParts.DLL
----------------------------------------
System.Composition.Hosting
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/System.Composition.Hosting.DLL
----------------------------------------
System.Composition.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/System.Composition.Runtime.DLL
----------------------------------------
System.Composition.AttributedModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/System.Composition.AttributedModel.DLL
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
Microsoft.DiaSymReader
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.23.22804
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/Microsoft.DiaSymReader.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
ArcadeMakerEngine
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/ArcadeMaker.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ArcadeMakerEngine
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ArcadeMaker%20DEMO%20T4.7.2/Files/ArcadeMaker.exe
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ArcadeMakerSources** [comment]
@rodrigo1593 thanks for reporting. I would suggest you to not use the background/sprite editor at this time, as it's really unfinished, buggy and lacks tons of possibilities

**Comment by rodrigo1593** [comment]
i will continue reporting them individually anyways man :)
